# Using this distribution because the default distribution does not have a working Ruby 1.8.7
dist: trusty

language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.6
  - 2.2.2

# todo - Remove this once TravisCI fixes their bundler issue (https://github.com/alphagov/govuk_template/pull/186)
before_install:
  - gem install bundler -v 1.9.10

script: bundle exec rake cuketagger:ci_build
